### ISSUE TITLE
Link (Backend) Per Cohort Zoom Link 

### ISSUE THREAD

**Issue by DeeJaeMann** [L-Carr/Platoon-Console#117]
Either new model or add-on to current for tracking links associated with a cohort

IE: Zoom link

**Comment by L-Carr** [comment]
Link Name | Cohort Name | Program | Link URL
-- | -- | -- | --
Zoom | Whiskey | Full Stack   Development Course | https://www.google.com
Zoom | Whiskey | Full Stack   Development Course | https://www.google.com



</body>

</html>
Link Name	Cohort Name	Program	Link URL
Zoom	Whiskey	Full Stack Development Course 	https://www.google.com/
Zoom	Whiskey	Full Stack Development Course 	https://www.google.com/
