### ISSUE TITLE
Watch Code Platoon Videos from Dashboard - Frontend/Backend - Youtube API Implementation(Stretch Goal)

### ISSUE THREAD

**Issue by nekablair** [L-Carr/Platoon-Console#65]
Integrate videos from Code Platoon in one place in student and instructor dashboard/homepage

**Comment by its-michaelroy** [comment]
Reopening to add the order-by date/title attribute for the videos page

**Comment by its-michaelroy** [comment]
Reopening to add Card container to homepage
