### ISSUE TITLE
Build Dashboard/Homepage for Instructors

### ISSUE THREAD

**Issue by nekablair** [L-Carr/Platoon-Console#8]
Ability to have list of student status, pairs, demo list(sequential for MVP)

**Comment by dagaither** [comment]
I believe the plan is still to just conditionally render our existing Homepage based on the user's `user_groups` value (Students vs Instructors). That's what was discussed today.  If so we shouldn't need a separate page for this.

Instructors and students would see near identical dashboards, however one single card would render differently, and this card would hold the user's group-specific links.  

Likely this would be the Daily Tasks card for students, which for instructors would render something like Instructor Tools.

**Comment by L-Carr** [comment]
Not Needed.
