### ISSUE TITLE
Bug-Register Page Not Whitelisted

### ISSUE THREAD

**Issue by nekablair** [L-Carr/Platoon-Console#98]
```javascript
if (
      !isAuthenticated &&
      !/^\/(login|forgot-password|change-password\/)/.test(location.pathname)
    ) {
      navigate('/login');
    }
  }, [navigate, location.pathname]); 
```

above is missing **register** page

**Comment by nekablair** [comment]
@dagaither are you tracking this? Do you want me to fix this bug?

**Comment by dagaither** [comment]
This should be fixed already @nekablair.  It was done kind of on-the-fly ramping up to the demo, and probably went in  with my third to last PR.  Thanks for following up on this.
